### PR TITLE
Support for React 17

### PR DESCRIPTION
**Pull request by blockbasti**

### CODE REVIEW

**Comment by rmanium** [comment]
LGTM, everything seems to be working fine

**Review by rmanium — APPROVED** [review]

**Comment by irdkwmnsb** [comment]
LGTM! Can't use it in new projects!

**Comment by Rukeith** [comment]
any update?

**Comment by niuware** [comment]
There is no restriction for using react 17.x.x with this package. Currently a warning will be displayed when using this package under a package with a react greater version than `16.8.6`. 

I just need to verify `mui-rte` can work correctly with react 17 and will update the peer dependencies version range. For now you can just simply use the react version you need.

**Comment by SerbanCarjan** [comment]
@niuware I cannot install the mui-rte package in a create-react-app / material-ui environment due to the React version:

``` npm i mui-rte --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.3
npm ERR!   node_modules/@material-ui/core
npm ERR!     @material-ui/core@"^4.11.3" from the root project
npm ERR!     peer @material-ui/core@">=4.1.0 <5" from mui-rte@1.28.0
npm ERR!     node_modules/mui-rte
npm ERR!       mui-rte@"*" from the root project
npm ERR!     1 more (@material-ui/icons)
npm ERR!   2 more (react-dom, @material-ui/icons)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from mui-rte@1.28.0
npm ERR! node_modules/mui-rte
npm ERR!   mui-rte@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Do you recommend installing using the `--force` or `--legacy-peer-deps` flags?

**Comment by niuware** [comment]
Version [1.29.0](https://github.com/niuware/mui-rte/tree/1.29.0) allows the use of React `17.0.x`.

**Pull request closed without merging**
