### PR TITLE
Added image paste and upload support

### PR DESCRIPTION
**Pull request by robnewton**

### CODE REVIEW

**Comment by robnewton** [comment]
Here's a sample implementation of the onUpload handler that calls a Lambda function using Axios that handles uploading the image to an S3 bucket.

```
  onUpload = (file) => {
    return new Promise(function (resolve, reject) {
      axios({
        method: 'POST',
        url: 'https://www.mywebsite.com/my/lambda/url',
        data: {file: file.body}
      })
        .then(res => {
          resolve({ 'publicUrl': `${res.data.publicUrl}` })
        })
        .catch(err => {
          resolve({ 'publicUrl': `${file.body}`, error: `Error uploading the image: ${err}`})
        })
    })
  }
```

Then there is the Lambda contents

```
var AWS = require('aws-sdk');

const S3_KEY = 'my-access-key';
const S3_SECRET = 'my-access-secret';
const S3_REGION = 'us-east-1';
const S3_BUCKET = 'my-bucket';
const S3_FOLDER = 'my-folder';
const log = true;

exports.handler = async (event, context) => {
  try {
    if (log) console.log('Pasted Image Uploader Called!')
    AWS.config.update({ accessKeyId: S3_KEY, secretAccessKey: S3_SECRET, region: S3_REGION })

    let filename = 'something-unique'
    let imageFileName = `${S3_FOLDER}/${filename}.png`  //TODO: derive this from the file passed

    const bodyParsed = JSON.parse(event.body)
    var s3Bucket = new AWS.S3({ params: { Bucket: S3_BUCKET } })
    var buf = new Buffer(bodyParsed.file.replace(/^data:image\/\w+;base64,/, ""), 'base64')
    var data = {
      Key: imageFileName,
      Body: buf,
      ContentEncoding: 'base64',
      ACL: 'public-read'
    }

    await s3Bucket.putObject(data).promise()
    const publicUrl = `https://${S3_BUCKET}.s3.amazonaws.com/${imageFileName}`
    if (log) console.log(`Uploaded ${publicUrl}`)

    return {statusCode: 200, body: JSON.stringify({ publicUrl: publicUrl })}
  } catch (err) {
    if (log) console.log('Location Image Uploader Failed!', JSON.stringify(err))
    return {statusCode: 500, body: JSON.stringify({ msg: err.message })}
  }
}
```

**Comment by robnewton** [comment]
Any ETA on getting this pulled and on NPM?

**Comment by niuware** [comment]
> Any ETA on getting this pulled and on NPM?

Sorry for the long wait. I have checked the PR but I feel it would be better to generalize the paste feature case. I am also not sure if it is a good idea to add the upload feature directly into the editor, which is not its core job. I will gather some ideas taking as a base what you provided and I'll share them when ready.

**Comment by robnewton** [comment]
Thanks and I appreciate the desire to abstract the copy paste case. We've went ahead and used my fork in prod but I'd rather stay on your version as soon as possible for the benefits of collective maintenance. If you are open to discussing your ideas with me, I'd be happy to work on it. Just let me know.

**Comment by niuware** [comment]
Can you base this PR to `master` instead?

**Comment by artik1327** [comment]
Hello, is this functionality coming out soon?

**Comment by niuware** [comment]
Hi @artik1327 This was implemented in version `1.18.0`. cc @robnewton 

An example can be found [here](https://github.com/niuware/mui-rte/blob/master/examples/async-image-upload/index.tsx).

**Pull request closed without merging**
